# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NextcloudPhonetrack
                                 A QGIS plugin
 Nextcloud Phonetrack Link imports Points/ Lines from a Nextcloud instance.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-16
        copyright            : (C) 2021 by Joachim Beerwerth
        email                : joachim.beerwerth@tu-dortmund.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NextcloudPhonetrack class from file NextcloudPhonetrack.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .NextcloudPhonetrack import NextcloudPhonetrack
    return NextcloudPhonetrack(iface)
